language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "2.7"
    env: TEST_SUITE=test-py2-legacy-support
  - python: "3.6"
    env: TEST_SUITE=test-static-analysis
install:
  - tools/provision --force
  - source zulip-api-py*-venv/bin/activate
script:
  - tools/$TEST_SUITE
  - wget https://github.com/houstondatavis/slack-export/archive/master.zip
  - mv master.zip slack-export-master.zip
  - zulip/integrations/slack/slackdata2zulipdata.py $PWD/slack-export-master.zip
after_success:
  - pip install codecov
  - codecov
